### ISSUE TITLE
[Feature request] Support for Open in Octal

### ISSUE THREAD

**Issue by quanganhdo** [dangwu/Octal#210] opened 2021-04-27 05:27 UTC
It'd be great if Octal can be launched from Safari when viewing a HN thread.

**Comment by dangwu** [comment] 2021-04-28 03:27
How would it work? Via Sharing to Octal?

**Comment by quanganhdo** [comment] 2021-04-28 04:10
Yeah, like an action extension to launch Octal with the current HN discussion.

**Comment by jlongman** [comment] 2021-11-06 12:00
https://www.icloud.com/shortcuts/e22979673496405d8e58f997c2765761
 This was my version.

**Comment by dangwu** [comment] 2023-07-06 14:57
Duplicate of https://github.com/dangwu/Octal/issues/236

also there is now a share extension in 4.12

**Closed by dangwu** 2023-07-06 14:57 UTC
