### ISSUE TITLE
App does not show a heart beside posts that were favorited outside the app

### ISSUE THREAD

**Issue by bvisch** [dangwu/Octal#221] opened 2021-06-10 14:21 UTC
Upon clicking, the message "Something went wrong" appears. Recently it seems that this issue has been happening with favorites submitted from within the app as well.

**Comment by danawoodman** [comment] 2021-06-11 00:13
I can confirm that this message shows up any time I attempt to favorite something but the actual favorite shows up in my account's favorites list

**Comment by dangwu** [comment] 2021-06-11 02:16
Thanks for the reports! I’ll check it out

**Comment by dangwu** [comment] 2021-06-13 00:07
Should be fixed now with 4.10.0! It's very difficult to get favorites working perfectly because it relies on HTML parsing and dodging HN's DDOS warnings, but it seems to work well enough for now...

**Closed** 2021-06-13 00:07 UTC

**Comment by bvisch** [comment] 2021-06-30 03:38
Thanks for fixing it so quickly @dangwu!
