### ISSUE TITLE
Favourite stories don’t load.

### ISSUE THREAD

**Issue by SuperTachyon** [dangwu/Octal#92] opened 2019-06-17 00:29 UTC
I’m experiencing empty list of stories in favourites, while I do have some checking from HN website. 

Newly favourited stories seem to stay but then disappear afterwards.

**Comment by dangwu** [comment] 2019-06-17 02:08
Thanks for the report. This is a known issue and I have a fix coming very
soon. Force killing and restarting the app may fix it for you in the mean
time. The root cause is the HN website returning “too many requests” errors
for the favorites fetch.

**Comment by dangwu** [comment] 2019-06-23 07:10
This should be resolved with 3.7.0

**Closed by dangwu** 2019-06-23 07:10 UTC
