### ISSUE TITLE
Interesting layout glitch

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#27] opened 2019-02-08 00:26 UTC
I can't figure out exact steps to reproduce this bug yet, but this squished UI (see the bottom of the screenshot below) just happened to me on 2.11.1

To fix it, I rotated my phone to landscape and then back to portrait.

I will post again if I can figure out how to reliably reproduce.

![image](https://user-images.githubusercontent.com/1992842/52451744-3b8acf00-2b0e-11e9-8dd0-48de16bcc221.png)

**Comment by dangwu** [comment] 2019-02-08 08:07
You're killing it with these bug finds! This happened once to me today too, but I also couldn't reproduce it.

**Comment by dangwu** [comment] 2019-03-01 18:58
Going to close this as I haven't seen it since. Feel free to reopen if you repro!

**Closed by dangwu** 2019-03-01 18:58 UTC

**Comment by luckman212** [comment] 2019-03-01 19:09
Sure, I haven't hit it again either. App is working 100%!

**Comment by luckman212** [comment] 2019-03-09 20:18
I don't know how, but this bug returned again in 2.16.1...

![9268890B-E385-4A4C-BB9A-889DF11A0C48](https://user-images.githubusercontent.com/1992842/54076883-8bc88e80-427e-11e9-9155-093395e7cc66.jpeg)
