### ISSUE TITLE
[Bug] Can't copy URLs anymore

### ISSUE THREAD

**Issue by luckman212** [dangwu/Octal#107] opened 2019-09-26 12:08 UTC
Related to #103 maybe?

Since 3.10.0, it's not possible to copy URLs anymore with a long press. Long press just places the selection somewhat randomly on words within the URL but user still needs to drag the handles and manually select the start/end and then copy.

**Comment by dangwu** [comment] 2019-09-30 17:12
Adding long press to copy a URL in the next version

**Comment by luckman212** [comment] 2019-09-30 17:22
Excellent!

**Comment by dangwu** [comment] 2019-10-01 22:22
Fixed in 3.11.0, out now

**Comment by luckman212** [comment] 2019-10-02 13:22
Thank you!

It could be an iOS13 bug (I am on 13.1.2 now) but it seems like I can only long press on a link "once" to copy it. If I scroll to another part of the comments page, copy a different link and then scroll back and try to copy the original link again, it does not copy - it just reverts to the previous behavior of selecting a part of the text. Here's a little screen recording, I wish it showed my finger presses but I don't know how to do that.

![longpress](https://user-images.githubusercontent.com/1992842/66047667-2710a200-e4f6-11e9-92b7-8f07866e1739.png)

**Comment by dangwu** [comment] 2019-10-02 18:06
Shoot; I know exactly what the issue is. I was trying to be smart about
multiple long presses triggering at the same time which was spamming toast
notifications. Will fix!

**Closed** 2019-11-22 07:59 UTC
