### ISSUE TITLE
[Feature] Grey our text header when read comments

### ISSUE THREAD

**Issue by Altrum** [dangwu/Octal#134] opened 2020-01-29 18:52 UTC
I think it’s hard to see what I’ve already glanced over if the header isn’t grayed out even when I’ve read the comments.

Could you make it so that clicking the comments section also grays out the post box?

**Comment by dangwu** [comment] 2020-03-18 17:41
Will add this soon

**Comment by dangwu** [comment] 2020-03-18 17:44
Duplicate of #91

**Closed by dangwu** 2020-03-18 17:44 UTC
