### ISSUE TITLE
[Bug] Links too easy to open when scrolling

### ISSUE THREAD

**Issue by jxcl** [dangwu/Octal#106] opened 2019-09-25 21:52 UTC
When I'm scrolling through the comments section, I frequently open links accidentally. It seems that a begin touch event is all that is necessary to open a link now, instead of a begin and an end touch event that both happen on the link. This has made scrolling without opening links very difficult.

I didn't notice this issue before, maybe the behavior has changed?

**Comment by dangwu** [comment] 2019-09-25 21:53
Duplicate of #103. Fix is coming soon - waiting for Apple approval

**Closed by dangwu** 2019-09-25 21:53 UTC
